### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by wode2016501** [corsicanu/android_kernel_samsung_universal9820#3]
.h
  CC      init/version.o
  AR      init/built-in.o
  AR      built-in.o
  LD      vmlinux.o
  MODPOST vmlinux.o
WARNING: modpost: Found 2 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
/home/wode/s10/kernel/GCC/aarch64-cruel-elf-master/bin/aarch64-cruel-elf-ld: warning: -z norelro ignored
/home/wode/s10/kernel/GCC/aarch64-cruel-elf-master/bin/aarch64-cruel-elf-ld: drivers/iommu/exynos-pcie-iommu.o: in function `exynos_sysmmu_irq':
/home/wode/s10/kernel/android_kernel_samsung_universal9820/drivers/iommu/exynos-pcie-iommu.c:458: undefined reference to `dhd_smmu_fault_handler'
/home/wode/s10/kernel/GCC/aarch64-cruel-elf-master/bin/aarch64-cruel-elf-ld: drivers/battery_v2/mfc_charger.o: in function `mfc_chg_set_property':
/home/wode/s10/kernel/android_kernel_samsung_universal9820/drivers/battery_v2/mfc_charger.c:3473: undefined reference to `spu_firmware_signature_verify'
/home/wode/s10/kernel/GCC/aarch64-cruel-elf-master/bin/aarch64-cruel-elf-ld: drivers/ccic/max77705_usbc.o: in function `max77705_firmware_update_sys':
/home/wode/s10/kernel/android_kernel_samsung_universal9820/drivers/ccic/max77705_usbc.c:820: undefined reference to `spu_firmware_signature_verify'
/home/wode/s10/kernel/GCC/aarch64-cruel-elf-master/bin/aarch64-cruel-elf-ld: drivers/sensorhub/brcm/bbdpl/bbd.o: in function `bbd_urgent_patch_read':
/home/wode/s10/kernel/android_kernel_samsung_universal9820/drivers/sensorhub/brcm/bbdpl/bbd.c:894: undefined reference to `spu_firmware_signature_verify'
Makefile:1137: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1
wode@wode:~/s10/kernel/android_kernel_samsung_universal9820$ grep  spu_firmware_signature_verify'

![2021-01-15 18-53-10屏幕截图](https://user-images.githubusercontent.com/22125765/104716511-0445e380-5763-11eb-9095-2e2617fcadf2.png)

**Comment by corsicanu** [comment]
Not sure i understand what you want...? Can you use **words**?
